app = "smart-app-1160"
github = "https://github.com/rahul-nife/react_password_generator"
id = "565fbbd2b5f72e8e8ba4bfb03df97eb4c2399d94a23f3f615a57996c93bd12fd1d9bcc6786f20c0a96d2e8aa61fb1a33"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "GitHub"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "500m"
    memory = "1Gi"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "250m"
    memory = "512Mi"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
