name: Deploy to Nife

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy to Nife
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Nife
        uses: nifetency/nife-actions@2.4
        env:
          NIFE_ACCESS_TOKEN: ${{ secrets.NIFE_ACCESS_TOKEN }}
        with:
          args: "deploy --remote-only"
