name: Deploy to Nife

on:
  push:

jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs nifectl deploy.
      - uses: nifetency/nife-actions@2.4
        env:
          NIFE_ACCESS_TOKEN: ${{ secrets.NIFE_ACCESS_TOKEN }}
        with:
          args: "deploy --remote-only"

eslint:
  name: Run ESLint
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Installing project dependencies
      run: npm install

    - name: Install ESLint and TypeScript packages
      run: npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin

    - name: Running ESLint
      run: npm run lint
      env:
        CI: true
